services:
  # El frontend ahora es Nginx sirviendo los archivos compilados
  frontend:
    build:
      context: ./frontend
      # Le decimos que use el Dockerfile que acabamos de crear
      dockerfile: Dockerfile
    ports:
      - "80:80" # Nginx corre en el puerto 80
    environment:
      # Las variables de Vite deben estar en el build,
      # pero si necesitas variables en Nginx, irían aquí.
      # Para la API, deberías configurar Nginx como proxy (un paso más avanzado).
      # Por ahora, asumimos que tu build de Vite ya tiene la URL de la API.
      # Para hacerlo bien, deberías usar NGINX como reverse proxy.
      VITE_API_URL: /api # Ejemplo si usaras un proxy
    depends_on:
      - auth-service

  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000" # Aún exponemos el auth-service
    environment:
      # ¡IMPORTANTE! Actualiza esto a tu URL de producción
      - REDIRECT_URI=http://tum-dominio.com/callback 
      - CLIENT_ID=my-client-id
      - CLIENT_SECRET=my-client-secret
      - AUTH_URL=https://accounts.google.com/o/oauth2/v2/auth
      - TOKEN_URL=https://oauth2.googleapis.com/token
      - SCOPE=openid email profile
    command: ["npm", "run", "start"] # Usa el comando de 'start' (no 'dev')